#!/usr/bin/env python3

import os
import sys
import argparse
from lxml import etree

signature = "Copyright (c) 2015 Trevor Gamblin <tvgamblin@gmail.com>"

license = """

    Copyright (c) 2015 Trevor Gamblin <tvgamblin@gmail.com>


    Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

parser = argparse.ArgumentParser(description="create a file with desired signature and license information")

parser.add_argument("-s", "--signature", help="add a signature", action="store_true")
parser.add_argument("-l", "--license", help="add license to new file", action="store_true")

parser.add_argument("target")

args = parser.parse_args()

#function for prepending text to an existing file
def prepend_to_file(text, target):
    with open(target, 'r') as original:
        data = original.read()
    with open(target, 'w') as modified:
        modified.write(text + "\n" + data)

#writes to file if doesn't already exist
def write_to_file(text, target):
    with open(target, "wt") as out_file:
        out_file.write(text)


def create_file(file_name):
    cdir = os.getcwd()
    if os.path.isfile(file_name):
        print("%s already exists in %s. Use '-s' to prepend signature, '-l' to prepend license, or create a file by specifying no options." % (file_name, cdir))
    else:
        with open(file_name, "wt") as f:
            print("Created %s in directory %s." % (file_name, cdir))



if __name__ == "__main__":
    if args.target:
        if args.signature:
            create_file(args.target)
            prepend_to_file(signature, args.target)
        elif args.license:
            create_file(args.target)
            prepend_to_file(license, args.target)
        else:
            create_file(args.target)
    else:
        for arg in sys.argv[1:]:
            print("Unknown argument %s" % (arg))
